In [20]:
from scripts.preprocess import small_data, normalize_image
from utils.params import DIRECTORY_Y, DIRECTORY_X, PROCESSED_DIR, MODEL_DIR, VISUALIZATION_DIR, SUBSTRING, NUM_FILES, IMAGE_SIZE
import numpy as np

In [4]:
X_train, y_train = small_data(DIRECTORY_Y, DIRECTORY_X, SUBSTRING, NUM_FILES)

In [6]:
X_train.shape

(1000, 85, 85, 3)

In [9]:
X_train

array([[[[ 8099,  8657,  8016],
         [ 8179,  8742,  8071],
         [ 8343,  9003,  8130],
         ...,
         [ 8062,  8635,  8028],
         [ 8021,  8615,  7990],
         [ 8261,  8801,  8132]],

        [[ 8167,  8707,  8085],
         [ 8146,  8710,  8062],
         [ 8266,  8904,  8093],
         ...,
         [ 8108,  8704,  8061],
         [ 8173,  8787,  8083],
         [ 8192,  8720,  8129]],

        [[ 8115,  8711,  8068],
         [ 8100,  8717,  8025],
         [ 8121,  8748,  8021],
         ...,
         [ 8208,  8738,  8148],
         [ 8179,  8873,  8101],
         [ 8158,  8829,  8130]],

        ...,

        [[ 8138,  8739,  8030],
         [ 8117,  8780,  8031],
         [ 8139,  8859,  8011],
         ...,
         [ 8032,  8547,  7982],
         [ 8030,  8463,  7982],
         [ 7951,  8370,  7917]],

        [[ 8054,  8701,  8003],
         [ 8076,  8756,  8002],
         [ 8095,  8725,  7949],
         ...,
         [ 8036,  8564,  7988],
         [ 8

In [11]:
X_train_norm = normalize_image(X_train)

In [8]:
y_train.shape

(1000, 85, 85)

In [16]:
y_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 0, 1]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        ...,
        [0, 0, 0, ..., 

In [17]:
X_train.max()

39853

In [18]:
X_train.min()

0

In [23]:
np_xtrain = np.load('../data/processed/X_train.npy')

In [24]:
np_xtrain

array([[[[ 8099,  8657,  8016],
         [ 8179,  8742,  8071],
         [ 8343,  9003,  8130],
         ...,
         [ 8062,  8635,  8028],
         [ 8021,  8615,  7990],
         [ 8261,  8801,  8132]],

        [[ 8167,  8707,  8085],
         [ 8146,  8710,  8062],
         [ 8266,  8904,  8093],
         ...,
         [ 8108,  8704,  8061],
         [ 8173,  8787,  8083],
         [ 8192,  8720,  8129]],

        [[ 8115,  8711,  8068],
         [ 8100,  8717,  8025],
         [ 8121,  8748,  8021],
         ...,
         [ 8208,  8738,  8148],
         [ 8179,  8873,  8101],
         [ 8158,  8829,  8130]],

        ...,

        [[ 8138,  8739,  8030],
         [ 8117,  8780,  8031],
         [ 8139,  8859,  8011],
         ...,
         [ 8032,  8547,  7982],
         [ 8030,  8463,  7982],
         [ 7951,  8370,  7917]],

        [[ 8054,  8701,  8003],
         [ 8076,  8756,  8002],
         [ 8095,  8725,  7949],
         ...,
         [ 8036,  8564,  7988],
         [ 8